version: "3.6"
services:
  gitlab:
    image: "yrzr/gitlab-ce-arm64v8:latest"
    restart: always
    hostname: "gitlab.example.com"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'password'
        nginx['redirect_http_to_https'] = true

        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - /srv/gitlab-ce/conf:/etc/gitlab:z
      - /srv/gitlab-ce/logs:/var/log/gitlab:z
      - /srv/gitlab-ce/data:/var/opt/gitlab:z
    shm_size: "256m"
