version: "3.6"
services:
  gitlab:
    image: yrzr/gitlab-ce-arm64v8:latest
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    volumes:
      - $GITLAB_HOME/conf:/etc/gitlab:z
      - $GITLAB_HOME/logs:/var/log/gitlab:z
      - $GITLAB_HOME/data:/var/opt/gitlab:z
    shm_size: "256m"
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
configs:
  gitlab:
    file: ./gitlab.rb
secrets:
  gitlab_root_password:
    file: ./root_password.txt
