version: "3.6"
services:
  gitlab:
    image: yrzr/gitlab-ce-arm64v8:latest
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    volumes:
      - /srv/gitlab-ce/conf:/etc/gitlab:z
      - /srv/gitlab-ce/logs:/var/log/gitlab:z
      - /srv/gitlab-ce/data:/var/opt/gitlab:z
    shm_size: "256m"
    environment:
      GITLAB_OMNIBUS_CONFIG: "nginx['redirect_http_to_https'] = true"
    secrets:
      - gitlab_root_password
configs:
  gitlab:
    file: ./gitlab.rb
secrets:
  gitlab_root_password:
    file: ./root_password.txt
